### ISSUE TITLE
Bug when creating Reverse-delegated Zones

### ISSUE THREAD

**Issue by alexkiousis** [grnet/webdns4#17]
Το webdns έχει ένα feature που όταν προσθέτεις NS record που έχει ένα dash ('-') μέσα πάει να φτιάξει με την μία και τα CNAME για το delegation.

Κάτι σκάει εκεί.

**Comment by vitsalis** [comment]
Με domain name `.2.0.192.in-addr.arpa` και input `192-29` δημιουργουνται 8 CNAME records κανονικα.

Υπαρχει καποιο συγκεκριμενο input ωστε να κανω reproduce;
